export interface AuthRegisterAPI {
	success: boolean;
	user: User;
}

export interface User {
	name: string;
}

// Generated by https://quicktype.io

export interface AuthLoginAPI {
	success: boolean;
	page: string;
	user: { name: string };
}
